{% set name = "auth0-python" %}
{% set version = "4.13.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/auth0_python-{{ version }}.tar.gz
  sha256: 72f58bd26b078e3b493e4d24928cc75fa41842aae35cef488ed6f8db0fb701fb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - urllib3 >=2.2.3
    - python >={{ python_min }}
    - aiohttp >=3.10.11
    - pyjwt >=2.8.0
    - cryptography >=43.0.1
    - requests >=2.32.3

test:
  imports:
    - auth0
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/auth0/auth0-python
  summary: Auth0 Python SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
