{% set name = "auth0-python" %}
{% set version = "4.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auth0_python-{{ version }}.tar.gz
  sha256: e175b1c741a50d59000702baf656aa3856658967a5439996ba5dc57169f1ba4a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7,<4.0
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - python >=3.7.0,<4.0.0
    - aiohttp >=3.8.5,<4.0.0
    - pyjwt >=2.8.0,<3.0.0
    - cryptography >=41.0.3,<42.0.0
    - pyopenssl >=23.2.0,<24.0.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - auth0
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/auth0/auth0-python
  summary: Auth0 Python SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
