{% set name = "auth0-python" %}
{% set version = "4.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auth0_python-{{ version }}.tar.gz
  sha256: 5cf8be11aa807d54e19271a990eb92bea1863824e4863c7fc8493c6f15a597f1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning >=1.0.0,<2.0.0
    - pip
  run:
    - urllib3 >=2.0.7,<3.0.0
    - python >=3.8
    - aiohttp >=3.8.5,<4.0.0
    - pyjwt >=2.8.0,<3.0.0
    - cryptography >=42.0.4,<43.0.0
    - pyopenssl >=23.2.0,<24.0.0
    - requests >=2.31.0,<3.0.0

test:
  imports:
    - auth0
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/auth0/auth0-python
  summary: Auth0 Python SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
