{% set name = "auth0-python" %}
{% set version = "4.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auth0-python-{{ version }}.tar.gz
  sha256: a2bf65aef096053adb461283b35d8a548ba4a1ea364fc49bdac7b1e7b0df02b7

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.14.0
    - pyjwt >=2.6.0

test:
  imports:
    - auth0
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/auth0/auth0-python
  summary: Auth0 Python SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
