{% set name = "auth0-python" %}
{% set version = "4.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/auth0-python-{{ version }}.tar.gz
  sha256: 61ff3f36643281d8a4417bfdb14ba440428a77e15ca523e719b6e2f24cd5c8ba

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - requests >=2.14.0
    - pyjwt >=2.6.0

test:
  imports:
    - auth0
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/auth0/auth0-python
  summary: Auth0 Python SDK
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
